#
# Makefile to add FIH driver for kernel driver build
obj-$(CONFIG_FIH_UNUSEGPIO) += fih_unusegpio.o
obj-$(CONFIG_FIH_HWID) += fih_hwid.o
obj-$(CONFIG_FIH_INFO) += fih_info.o
obj-$(CONFIG_FIH_NVRF) += fih_nv_rf.o
obj-$(CONFIG_FIH_NVCUST) += fih_nv_cust.o
obj-$(CONFIG_FIH_E2P) += fih_e2p.o
obj-$(CONFIG_FIH_CPU) += fih_cpu.o
obj-$(CONFIG_FIH_DRAM) += fih_dram.o
obj-$(CONFIG_FIH_APR) += fih_apr.o
obj-y += fih_touch.o
obj-$(CONFIG_FIH_SECBOOT) += fih_secboot.o
obj-$(CONFIG_FIH_BLOG) += fih_blog.o
obj-$(CONFIG_FIH_UFSINFO) += fih_ufsinfo.o
obj-$(CONFIG_FIH_FVER) += fih_fver.o
obj-$(CONFIG_FIH_MFR) += fih_mfr.o
obj-$(CONFIG_FIH_SUT) += fih_sut.o
obj-y += fih_lcm.o
obj-$(CONFIG_FIH_DDRTEST) += fih_ddr_test.o
obj-y += fih_battery.o
