dtb-$(CONFIG_ARCH_MSM8998) += \
  msm8998-mtp_RCL_EVT0.dtb \
  msm8998-mtp_RCL_EVT1.dtb \
  msm8998-mtp_RCL_EVT2.dtb \
  msm8998-mtp_RCL_EVT21.dtb \
  msm8998-mtp_RCL_DVT0.dtb \
  msm8998-mtp_RCL_DVT1.dtb \
  msm8998-mtp_RCL_PVT.dtb \
  msm8998-mtp_RCL_MP.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
